<!DOCTYPE html>
<html lang="en"><head>
<script src="test_2_082025_files/libs/clipboard/clipboard.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tabby.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/popper.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="test_2_082025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content=" Lesley Chapman Hannah, Ph.D., M.S. College of Graduate Studies Northeast Ohio Medical University">
  <title>Descriptive Group-Level Summaries</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h2 style="color: #2A76DD;" class="title">Descriptive Group-Level Summaries</h2>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div style="font-size:20px;" class="quarto-title-author-name">
<br><br><span style="font-size:25px;"><strong>Lesley Chapman Hannah, Ph.D., M.S.</strong></span><br>College of Graduate Studies<br>Northeast Ohio Medical University 
</div>
</div>
</div>

</section>
<section class="slide level2">

<h3 id="lecture-goals">Lecture Goal(s)</h3>
<p><strong>Central focus:</strong></p>
<ul>
<li><p>descriptive analysis often compares groups defined by treatment, disease status, or cohort membership</p></li>
<li><p>discuss how group summaries and comparative plots reveal differences in location, spread, and distribution</p></li>
</ul>
<p>Here we ask:</p>
<blockquote>
<p><strong>How do group summaries and comparative plots reveal differences in location, spread, and distribution?</strong></p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="descriptive-group-analysis">Descriptive group analysis</h3>
<div style="font-size:0.67em">
<p>Descriptive Group Analysis involves:</p>
<ul>
<li>summarizing the full sample</li>
<li>stratifying by a clinically meaningful grouping variable</li>
<li>visualizing group-specific patterns</li>
<li>interpreting scientifically meaningful patterns and trends</li>
</ul>
<p>Where</p>
<ul>
<li><strong>overall summary</strong>: single description computed across all observations together</li>
<li><strong>group-specific summary</strong>: separate description computed within each subgroup</li>
<li><strong>comparative plot</strong>: visualization designed to compare groups directly</li>
<li><strong>scientific interpretation</strong>: the biomedical meaning assigned to observed differences in center, spread, or shape</li>
</ul>
</div>
</section>
<section id="lecture-roadmap" class="slide level2">
<h2>Lecture Roadmap</h2>
<div style="font-size:0.67em">
<p><strong>Key Terms</strong></p>
<ul>
<li><strong>group</strong>: a set of observations sharing the same category, such as treatment arm or disease class</li>
<li><strong>location</strong>: where values tend to be centered, often described by the mean or median</li>
<li><strong>spread</strong>: how variable the observations are, often described by the standard deviation or IQR</li>
<li><strong>distribution</strong>: the overall pattern of values, including center, spread, skewness, and tail behavior</li>
<li><strong>heterogeneity</strong>: meaningful variation across subgroups rather than within one pooled population alone</li>
</ul>
<p><strong>Tools [select]</strong>:</p>
<ul>
<li>mean and median by group<br>
</li>
<li>summary tables<br>
</li>
<li>boxplots<br>
</li>
<li>violin plots<br>
</li>
<li>interpretation of subgroup heterogeneity</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="group-comparisons-background">Group Comparisons: Background</h3>
<ul>
<li><p><code>group comparison</code> : asks whether the observed values of a variable look different once the sample is partitioned by a biologically or clinically meaningful categorical variable such as treatment arm, disease status, or cohort membership</p></li>
<li><p><code>group-level summaries and comparative plots</code> : describe how a variable behaves <strong>within user specified subgroups</strong> and then comparing those subgroup-specific descriptions across groups</p></li>
</ul>
<p><strong>General Applications</strong></p>
<ul>
<li>treatment groups may differ in average biomarker level</li>
<li>disease subtypes may differ in variability, not only in average level</li>
<li>two groups may have similar means but very different internal distributions</li>
<li>descriptive comparison is often the first step before any formal modeling or hypothesis testing</li>
</ul>
</section>
<section class="slide level2">

<h3 id="group-comparisons-background-1">Group Comparisons: Background</h3>
<div style="font-size:0.67em">
<ul>
<li><p><code>summary tables</code> : report either - median by group or means by group</p></li>
<li><p><code>mean</code>: measure of central tendency defined as the sum of all observed values divided by the number of observations</p>
<ul>
<li>every value contributes to the mean therefore very high or very low observations can pull the mean upward or downward</li>
</ul></li>
<li><p><code>median</code> : measure of central tendency defined as the middle value of a set of ordered observations</p>
<ul>
<li>most informative when we want a measure of central location that is less sensitive to skewness or unusually large values</li>
<li>right-skewed biomarkers <span class="math inline">\(\rightarrow\)</span> median often aligns more closely with the value observed for a typical observations [i.e.: patient]</li>
</ul></li>
<li><p><code>median by group</code>: subgroup-specific measure of central tendency defined as the middle value of the ordered observations within each group</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="approach-for-comparing-groups">Approach for Comparing Groups</h3>
<div style="font-size:0.67em">
<p><strong>Key things to ask when comparing groups</strong></p>
<ul>
<li><strong>sample size</strong>: are the groups similar in size, or are some summaries based on much smaller numbers of observations?</li>
<li><strong>location</strong>: do the means or medians differ across groups?</li>
<li><strong>spread</strong>: do the standard deviations or IQRs differ across groups?</li>
<li><strong>mean-median agreement</strong>: are the mean and median similar within groups, or do they diverge in ways that suggest skewness?</li>
<li><strong>clinical magnitude</strong>: are the observed differences large enough to matter scientifically, not only numerically?</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="plots-for-comparing-groups">Plots for comparing groups</h3>
<div style="font-size:0.67em">
<p><code>boxplot</code> : graphical summary of a quantitative variable that represents the ordered structure of the data using key percentiles and tail behavior</p>
<p>Display the following:</p>
<ul>
<li>minimum (or lower whisker endpoint)</li>
<li>first quartile (Q1 - 25th percentile)</li>
<li>median (Q2 - 50th percentile)</li>
<li>third quartile (Q3 - 75th percentile)</li>
<li>maximum (or upper whisker endpoint)</li>
</ul>
<p><code>violin plot</code>: graphical display of a quantitative variable that combines a smoothed estimate of the distribution (density) with key features of the data’s central tendency and spread</p>
<ul>
<li><strong>width of the violin</strong> → proportional to the density of observations at a given value</li>
<li><strong>central tendency</strong> → location of the median within the distribution</li>
<li><strong>multimodality</strong> → presence of multiple peaks (subpopulations)</li>
</ul>
<p><strong>Considerations for plot-based comparison across groups</strong></p>
<ul>
<li>is one group positioned higher or lower overall on the y-axis?</li>
<li>do some groups show stronger skewness or longer tails?</li>
<li>do any groups contain more extreme values?</li>
<li>does the shape suggest internal subgroup structure or heterogeneity within a treatment arm?</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="subgroup-heterogeneity">Subgroup Heterogeneity</h3>
<div style="font-size:0.67em">
<p><strong>subgroup heterogeneity</strong> :</p>
<ul>
<li><p>observations within a group are not all tightly clustered around one common pattern</p></li>
<li><p>presence of meaningful differences in the distribution, central tendency, variability, or relationships within distinct subgroups of a population</p></li>
<li><p>descriptive statistics - subgroup heterogeneity may appear as:</p>
<ul>
<li>wide IQR</li>
<li>large standard deviation</li>
<li>long whiskers in a boxplot</li>
<li>wide or irregular violin shape</li>
<li>multiple peaks in a histogram or violin plot</li>
<li>large differences between low and high observations within the same group</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="study-context-and-dataset-overview">Study Context and Dataset Overview</h3>
<div style="font-size:0.67em">
<p>Here we evaluate data from a randomized immunotherapy study designed to evaluate how treatment intensity influences both immune system activity and clinical outcomes</p>
<p><strong>Research Question</strong></p>
<blockquote>
<p>How do we describe and compare distributions across groups in biomedical data?</p>
</blockquote>
<blockquote>
<p>How does the distribution differ by treatment or disease category?</p>
</blockquote>
<p>Immunotherapy study follows patients in three arms:</p>
<ul>
<li>placebo</li>
<li>low dose immunotherapy</li>
<li>high dose immunotherapy</li>
</ul>
<p>For each patient, the study records multiple outcomes that reflect different dimensions of response:</p>
<ul>
<li><strong>interferon-gamma [IFN-γ] concentration</strong>: continuous biomarker of immune activation</li>
<li><strong>CD4+ T-cell count</strong>: continuous measure of immune system status</li>
<li><strong>clinical response class</strong> [i.e.: responder vs non-responder or ordinal response categories] : categorical outcome reflecting treatment efficacy</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="simulated-immunotherapy-dataset">Simulated Immunotherapy Dataset</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>group_df <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  patient_id treatment  ifng cd4_count response_class
  &lt;chr&gt;      &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;         
1 G001       High dose 24.6        818 Stable        
2 G002       High dose 17.6        655 Responder     
3 G003       Placebo   15.2        512 Stable        
4 G004       Low dose  12          703 Responder     
5 G005       Low dose  33.4        567 Progressive   
6 G006       High dose  7.78       751 Stable        
7 G007       Low dose   9.48       562 Responder     
8 G008       Low dose   8.92       631 Progressive   </code></pre>
</div>
</div>
<p><strong>Column descriptions</strong></p>
<ul>
<li><code>patient_id</code>: unique identifier for each patient in the study<br>
</li>
<li><code>treatment</code>: treatment arm assigned to the patient [<code>Placebo</code>, <code>Low dose</code>, <code>High dose</code>]
<ul>
<li>primary grouping variable used for comparisons across subgroups<br>
</li>
</ul></li>
<li><code>ifng</code>: interferon-gamma concentration, a continuous biomarker of immune activation measured for each patient<br>
</li>
<li><code>cd4_count</code>: CD4 T-cell count - a continuous measure of immune system status for each patient<br>
</li>
<li><code>response_class</code>: clinical response category for each patient [<code>Responder</code>, <code>Stable</code>, <code>Progressive</code>]
<ul>
<li>categorical outcome describing treatment response</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-mean-by-treatment-group">IFN-gamma: Mean by Treatment Group</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>group_df <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-4"><a href=""></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb3-5"><a href=""></a>    <span class="at">mean_ifng =</span> <span class="fu">mean</span>(ifng),</span>
<span id="cb3-6"><a href=""></a>    <span class="at">sd_ifng =</span> <span class="fu">sd</span>(ifng)</span>
<span id="cb3-7"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment     n mean_ifng sd_ifng
  &lt;chr&gt;     &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 High dose    67      20.7    8.22
2 Low dose     79      16.4    7.65
3 Placebo      64      12.6    7.04</code></pre>
</div>
</div>
<ul>
<li><code>mean</code>: summarizes the average level within each treatment arm</li>
<li><code>standard deviation</code>: shows variability among participants in the same arm</li>
</ul>
<p><strong>Interpretation</strong></p>
<ul>
<li><code>n</code> : number of patients that contribute to each treatment-specific summary</li>
<li><code>mean_ifng</code>: compares average IFN-gamma across arms and essentially comparing group <strong>location</strong></li>
<li><code>sd_ifng</code> compares within-group variability and therefore compares group <strong>spread</strong></li>
<li>If the high-dose arm has the largest mean, that suggests a higher central level of IFN-gamma in that group</li>
<li>If one arm has a larger standard deviation, that suggests greater patient-to-patient heterogeneity within that treatment condition</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-mean-by-treatment-group-1">IFN-gamma: Mean by Treatment Group</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>group_df <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-4"><a href=""></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb5-5"><a href=""></a>    <span class="at">mean_ifng =</span> <span class="fu">mean</span>(ifng),</span>
<span id="cb5-6"><a href=""></a>    <span class="at">sd_ifng =</span> <span class="fu">sd</span>(ifng)</span>
<span id="cb5-7"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment     n mean_ifng sd_ifng
  &lt;chr&gt;     &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 High dose    67      20.7    8.22
2 Low dose     79      16.4    7.65
3 Placebo      64      12.6    7.04</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p><code>treatment</code>: treatment arm defining each subgroup (<code>Placebo</code>, <code>Low dose</code>, <code>High dose</code>)<br>
</p></li>
<li><p><code>n</code>: number of patients within each treatment group (sample size for the subgroup)<br>
</p></li>
<li><p><code>mean_ifng</code>: average IFN-gamma concentration within the group<br>
</p></li>
<li><p><code>sd_ifng</code>: standard deviation of IFN-gamma within the group, quantifying variability around the mean</p></li>
<li><p>IFN-gamma levels increase across treatment intensity:</p>
<ul>
<li>Placebo ≈ 12.6 pg/mL<br>
</li>
<li>Low dose ≈ 16.4 pg/mL<br>
</li>
<li>High dose ≈ 20.7 pg/mL</li>
</ul></li>
<li><p>variability is present in all groups [SD ≈ 7–8] <span class="math inline">\(\rightarrow\)</span> indicating spread around the mean within each treatment arm</p></li>
<li><p>data suggest that IFN-gamma is right-skewed therefore the mean may be influenced by higher values<br>
</p></li>
<li><p>motivates comparing <strong>median and IQR</strong> as an additional summary of central tendency and spread</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-median-and-iqr-by-treatment-group">IFN-gamma: Median and IQR by Treatment Group</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>group_df <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-4"><a href=""></a>    <span class="at">median_ifng =</span> <span class="fu">median</span>(ifng),</span>
<span id="cb7-5"><a href=""></a>    <span class="at">iqr_ifng =</span> <span class="fu">IQR</span>(ifng),</span>
<span id="cb7-6"><a href=""></a>    <span class="at">median_cd4 =</span> <span class="fu">median</span>(cd4_count),</span>
<span id="cb7-7"><a href=""></a>    <span class="at">iqr_cd4 =</span> <span class="fu">IQR</span>(cd4_count)</span>
<span id="cb7-8"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  treatment median_ifng iqr_ifng median_cd4 iqr_cd4
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 High dose        19.1     9.07       647     158.
2 Low dose         14.9     8.82       567     118.
3 Placebo          11.4     6.68       538.    118.</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><code>treatment</code>: treatment arm defining each subgroup<br>
</li>
<li><code>median_ifng</code>: middle IFN-gamma value within each group</li>
<li><code>iqr_ifng</code>: spread of the middle 50% of IFN-gamma values within each group<br>
</li>
<li><code>median_cd4</code>: middle CD4 count within each group<br>
</li>
<li><code>iqr_cd4</code>: spread of the middle 50% of CD4 values within each group - <code>IFN-gamma and CD4</code>: show increasing central tendency across treatment groups**<br>
</li>
<li><code>IFN-gamma</code> : shows increasing variability - consistent with a right-skewed biomarker<br>
</li>
<li><code>median and IQR</code>: describe how the central bulk of the distribution shifts and spreads across groups</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-median-and-iqr-by-treatment-group-1">IFN-gamma: Median and IQR by Treatment Group</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>group_df <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-4"><a href=""></a>    <span class="at">median_ifng =</span> <span class="fu">median</span>(ifng),</span>
<span id="cb9-5"><a href=""></a>    <span class="at">iqr_ifng =</span> <span class="fu">IQR</span>(ifng),</span>
<span id="cb9-6"><a href=""></a>    <span class="at">median_cd4 =</span> <span class="fu">median</span>(cd4_count),</span>
<span id="cb9-7"><a href=""></a>    <span class="at">iqr_cd4 =</span> <span class="fu">IQR</span>(cd4_count)</span>
<span id="cb9-8"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  treatment median_ifng iqr_ifng median_cd4 iqr_cd4
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 High dose        19.1     9.07       647     158.
2 Low dose         14.9     8.82       567     118.
3 Placebo          11.4     6.68       538.    118.</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>Median and IQR show that both biomarker levels and their central spread increase with treatment intensity, with IFN-gamma exhibiting greater variability at higher doses</li>
</ul>
<p><strong>IFN-gamma median increases with treatment intensity</strong>: shift in the typical biomarker level across groups</p>
<ul>
<li>Placebo ≈ 11.4 pg/mL<br>
</li>
<li>Low dose ≈ 14.9 pg/mL<br>
</li>
<li>High dose ≈ 19.1 pg/mL</li>
</ul>
<p><strong>IQR for IFN-gamma</strong>: greater spread in the central distribution at higher treatment levels<br>
- Placebo ≈ 6.68<br>
- Low dose ≈ 8.82<br>
- High dose ≈ 9.07</p>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-median-and-iqr-by-treatment-group-2">IFN-gamma: Median and IQR by Treatment Group</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>group_df <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-4"><a href=""></a>    <span class="at">median_ifng =</span> <span class="fu">median</span>(ifng),</span>
<span id="cb11-5"><a href=""></a>    <span class="at">iqr_ifng =</span> <span class="fu">IQR</span>(ifng),</span>
<span id="cb11-6"><a href=""></a>    <span class="at">median_cd4 =</span> <span class="fu">median</span>(cd4_count),</span>
<span id="cb11-7"><a href=""></a>    <span class="at">iqr_cd4 =</span> <span class="fu">IQR</span>(cd4_count)</span>
<span id="cb11-8"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  treatment median_ifng iqr_ifng median_cd4 iqr_cd4
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 High dose        19.1     9.07       647     158.
2 Low dose         14.9     8.82       567     118.
3 Placebo          11.4     6.68       538.    118.</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p><strong>CD4 median also increases across treatment</strong>: higher typical immune cell counts with increased treatment intensity</p>
<ul>
<li>Placebo ≈ 538<br>
</li>
<li>Low dose ≈ 567<br>
</li>
<li>High dose ≈ 647</li>
</ul>
<p><strong>CD4 IQR</strong> : variability is similar for placebo and low dose, but more spread in the high dose group</p>
<ul>
<li>Placebo ≈ 118<br>
</li>
<li>Low dose ≈ 118<br>
</li>
<li>High dose ≈ 158</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>plot shows a dose-dependent increase in immune response with moderate variability across patients</li>
<li>median IFN-gamma increases from ~11.4 [placebo] to ~14.9 [low dose] to ~19.1 pg/mL [high dose]</li>
</ul>
<p>Median Comparison:</p>
<ul>
<li>high dose: median ≈ 19.1 pg/mL</li>
<li>low dose: median ≈ 14.9 pg/mL</li>
<li>placebo: median ≈ 11.4 pg/mL</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons-1">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-10-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>IQR Comparison:</p>
<ul>
<li>high dose group has the widest central spread <span class="math inline">\(\rightarrow\)</span> more variability in response across<br>
</li>
<li>consistent IFN-gamma levels across the placebo group <span class="math inline">\(\rightarrow\)</span> more tightly clustered IQR</li>
<li>high dose: IQR ≈ 9.07 pg/mL</li>
<li>low dose: IQR ≈ 8.82 pg/mL</li>
<li>placebo: IQR ≈ 6.68 pg/mL</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons-2">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-11-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>Tails and outliers:</p>
<ul>
<li>all groups have higher values extending into the upper tail regions</li>
<li>high dose outliers: ~38–43 pg/mL</li>
<li>low dose outliers: up to ~49 pg/mL</li>
<li>placebo outliers: up to ~53 pg/mL</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons-3">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key plot interpretation</strong></p>
<ul>
<li><code>violin plot</code> : shows both the distribution shape and density of IFN-gamma within each treatment group</li>
<li>width of the violin reflects the density of observations at that IFN-gamma level</li>
<li>widest sections indicate where values are most concentrated within each group</li>
<li>overall shape reveals distribution features such as skewness and multimodality</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons-4">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key plot interpretation</strong></p>
<ul>
<li>wider regions indicate values that occur more frequently within a group</li>
<li>narrow upper regions indicate fewer patients at high IFN-gamma levels</li>
<li>asymmetry in the violin can reveal skewness</li>
<li>differences in overall vertical placement still reflect differences in group location</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="ifn-gamma-group-comparisons-5">IFN-gamma: group comparisons</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p><strong>high dose group</strong>: greatest density around ~18–20 pg/mL with additional density extending into higher values [~30–40 pg/mL</p></li>
<li><p><strong>low dose group</strong>: centered lower with highest density around ~12–15 pg/mL</p></li>
<li><p><strong>placebo group</strong>: most concentrated around ~9–12 pg/mL</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="cd4-t-cell-count-group-comparison">CD4+ T-cell Count: Group Comparison</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Analysis Goals</strong></p>
<ul>
<li>compare median CD4+ T-cell count across treatment groups to assess differences in location</li>
<li>compare box heights to assess differences in central spread</li>
<li>compare whisker symmetry to assess whether the distributions appear roughly symmetric or more skewed</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="cd4-t-cell-count-group-comparison-1">CD4+ T-cell Count: Group Comparison</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-16-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>box plots of CD4+ T-cell count shows a dose-dependent improvement in immune function with moderate variability across patients</li>
<li>median CD4 count increases from ~538 cells/µL [placebo] to ~567 cells/µL [low dose] to ~647 cells/µL [high dose]</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="cd4-t-cell-count-group-comparison-2">CD4+ T-cell Count: Group Comparison</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-17-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>horizontal position of the bars shows the IFN-gamma range for each treatment arm</li>
<li>bar heights show how many patients fall in each interval</li>
<li>histograms show that IFN-gamma distributions shift upward from ~11.4 [placebo] to ~14.9 [low dose] to ~19.1 pg/mL [high dose]</li>
<li>right-skewness and outliers up to ~50 pg/mL indicates variable but dose-dependent immune response</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="summary">Summary</h3>
<div style="font-size:0.67em">
<ul>
<li>group-level summaries and plots transform raw biomedical data into interpretable evidence about how biological or clinical processes differ across populations</li>
<li>computed group-specific summaries:
<ul>
<li>mean → average level [sensitive to extreme values]</li>
<li>median → typical value [robust to skewness]</li>
<li>standard deviation / IQR → variability within groups</li>
</ul></li>
<li>used comparative visualizations:
<ul>
<li>boxplots → summarize quartiles, spread, and outliers</li>
<li>violin plots → reveal full distribution shape and density</li>
</ul></li>
<li>interpreted differences across groups in:
<ul>
<li>location [center of the distribution]</li>
<li>spread [variability]</li>
<li>distribution shape [skewness, tails, multimodality]</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="test_2_082025_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="test_2_082025_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1400,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>